### ISSUE TITLE
Missing SITE definition

### ISSUE THREAD

**Issue by kareefardi** [google/globalfoundries-pdk-libs-gf180mcu_fd_sc_mcu9t5v0#16]
## Expected Behavior
SITE definition for `GF018hv5v_green_sc9` in the tech lefs 

## Actual Behavior
No SITE defintion

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by QuantamHD** [comment]
```
SITE GF018hv5v_green_sc9
  SYMMETRY X Y ;
  CLASS core ;
  SIZE 0.56 BY 5.04 ;
END GF018hv5v_green_sc9
```

This is the correct SITE definition.
